name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test-reveal-secret:
    steps:
      env : 
        TESTSECRET : ${{secrets.TESTSECRETAPI}}
      - run: echo 'mon secret est $TESTSECRET'
