name: Static HTML Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Export GitHub secrets to environment variables
        run: |
          echo "TESTSECRETAPI=${{ secrets.TESTSECRETAPI }}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          TESTSECRETAPI: ${{ secrets.TESTSECRETAPI }}
          publish_dir: ./build
